version: '3.9'
services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    # Docker側とローカル側を同期
    volumes:
      - ./client:/usr/src/app
    environment:
      NODE_ENV: local
    ports:
      - 3000:3000
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    # Docker側とローカル側を同期
    volumes:
      - ./server:/usr/src/app
    environment:
      NODE_ENV: local
    ports:
      - 5000:5000
  db:
    # Docker HubからMySQL5.7の公式イメージをダウンロードしてくる指定
    image: mysql:8.0
    container_name: three_arrows_db
    # コンテナ内の環境変数を指定。環境変数を渡すとビルド時に設定してくれるDockerイメージがあるので、利用の際はDocker Hubのサイトで確認する
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: three_arrows
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'America/Vancouver'

    # 起動時のコマンド
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    # ディレクトリ同期。設定ファイルとMySQLのデータが保存される場所を同期している。コンテナは基本的に起動時に変更されてもコンテナ自体が止まるとデータが消えてしまうため、保存しておきたいものはホストマシンと同期しておく必要がある。
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
